wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715372492
    t:
      1:
      - 1
      - 12
      - 30
      - 55
      2:
      - 1
      - 12
      - 30
      - 55
      3:
      - 13
      - 23
      4: 3.11.7
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
